@baseurl = http://localhost:3000
@auth = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzMHBwZXgiLCJleHAiOjE2NjI3NTg5MDMsImlhdCI6MTY2Mjc1NTMwMywidHlwIjoiYm94In0.qOAAuF7J1MvbEen9mbC8sachNYp1yCduo7UdhEES_ibQDAb6CHX3vAEnPYB8rsecNbqrN0UTiktvUm-7cyJBTg
# @auth = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaWE5bXUiLCJleHAiOjE2NjI3NjIxNTQsImlhdCI6MTY2Mjc1ODU1NCwidHlwIjoibGlzdCJ9.R0YagkKCemn4XXfGl9c2CrDwkCiwDnOhCwNo2zJR6FPB-CmnzKxzMIr9eIRWeAiD1MbpOFEEk5-dawrDktB1Lw

POST {{baseurl}}/api/auth
Content-Type: application/json

{
  "code": "s0ppex",
  "password": "jimmy",
  "type": "box"
}

#####

POST {{baseurl}}/api/auth
Content-Type: application/json

{
  "code": "jia9mu",
  "password": "jimmy",
  "type": "list"
}

######

PUT {{baseurl}}/api/boxes/s0ppex
Authorization: {{auth}}
Content-Type: application/json

{
  "ownerName": "Jimmy Acero",
  "name": "Mi buzón navideño",
  "intro": "Hola familia, los invito a que me dejen sus deseos navideños"
}

#######

GET {{baseurl}}/api/lists/jia9mu

#####

POST {{baseurl}}/api/boxes/s0ppex/lists
Content-Type: application/json

{
  "listCode": "jia9mu",
  "showName": true
}

######

GET {{baseurl}}/api/boxes/s0ppex/last-lists?limit=3

######

GET {{baseurl}}/api/boxes/s0ppex/lists
Authorization: {{auth}}
